## 1.	Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files.Delete the found duplicate file.

In [10]:
import hashlib
import os

path = "D:\Python Assignment"
hashes = []

for (dir_path, dir_names, file_names) in os.walk(path):
    print(dir_path,dir_names,file_names)
    for filename in file_names:
        try:
            filepath = os.path.join(dir_path, filename)
            file = open(filepath, 'r')
            content = file.read().encode()
            file.close()
            message = hashlib.sha256(content)
            if message.hexdigest() not in hashes:
                hashes.append(message.hexdigest())
            else:
                os.remove(filepath)
        except Exception as e:
            print(e)

D:\Python Assignment [] ['text 2.txt', 'text 3.txt', 'text1.txt']


## 2.	Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters. Using these packages [random, strings]

In [18]:
import random
import string

password = []

password.extend(random.choices(string.ascii_uppercase, k=1))
password.extend(random.choices(string.ascii_lowercase, k=2))
password.extend(random.choices('0123456789',k=3))

strongpassword = ""
random.shuffle(password)

for i in range(6):
    strongpassword += password[i]
    
print("Here is your password:", strongpassword)

Here is your password: im1O26


## 3. Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

In [3]:
def prime_no(num):
    flag=False
    if num==1:
        return False
    elif num>1:
        for i in range(2,int((num/2)+1)):
            if (num%i) == 0:
                flag=True
                break
            else:
                flag=False
    if flag:
        return False
    else:
        return True

import numpy as np
arr_1=np.array([[1,2,3,4],[3,24,5,7]])
for i in range(len(arr_1)):
    for j in range(len(arr_1[i])):
        if prime_no(arr_1[i][j]):
            arr_1[i][j]=(arr_1[i][j]**3)
print(arr_1)

[[  1   8  27   4]
 [ 27  24 125 343]]


## 4.Python program to get the sum of every cubed value and its previous integer. 

In [4]:
import numpy as np

arr_1=np.array([[1,2,3,4],[8,3,5,7]])
sum_2=0

def prime_no(num):
    flag=False
    if num==1:
        return False
    elif num>1:
        for i in range(2,int((num/2)+1)):
            if (num%i) == 0:
                flag=True
                break
            else:
                flag=False
    if flag:
        return False
    else:
        return True

for i in range(len(arr_1)):
    for j in range(len(arr_1[i])):
        if prime_no(arr_1[i][j]):
            sum_2 = (arr_1[i][j]**3) + arr_1[i][j-1]
            
print(sum_2)

348


## 5.	Given two arrays, find their intersection. Examples:
**Input:  arr1[] = [1, 3, 4, 5, 7]
   arr2[] = [2, 3, 5, 6]**


In [32]:
arr1 = [1, 3, 4, 5, 7]
arr2 = [2, 3, 5, 6]

intersection_set = set(arr1).intersection(arr2)
intersection_list = list(intersection_set)

print(intersection_list)

[3, 5]


## 6. Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [35]:
arr = [[7 * (i * 7 + j) for j in range (1,7)] for i in range (7)]
print(arr)

last_element = arr[-1][-1]
print("Last element is:", last_element)

[[7, 14, 21, 28, 35, 42], [56, 63, 70, 77, 84, 91], [105, 112, 119, 126, 133, 140], [154, 161, 168, 175, 182, 189], [203, 210, 217, 224, 231, 238], [252, 259, 266, 273, 280, 287], [301, 308, 315, 322, 329, 336]]
Last element is: 336


##  7.Checker Board Patten using Numpy:

In [6]:
import numpy as np

def printcheckboard(n):
    final = []
    
    for i in range(n):
        final.append(list(np.tile([1,0],int(n/2))) if i%2==0 else list(np.tile([0,1],int(n/2))))
    print(np.array(final))
    
n = int(input("Enter Dimensions:"))
printcheckboard(n)

Enter Dimensions:7
[[1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


## 8.	Create a given Matrix:

[A, B, C, D
 E, F, G, H
 I, a, K, L
 M, N, o, P
 Q, R, S, T
 U, 0, W, O ]

## place all the vowels by np.nan A, E, I, O U  -- >  np.nan Return the count of the missing values

In [12]:
arr_1 = ['A','B','C','D',
         'E','F','G','H',
         'I','a','K','L',
         'M','N','o','P',
         'Q','R','S','T',
         'U','0','W','O']
ct=0
for i in range(0, len(arr_1)):
    if arr_1[i].lower() in "aeiou":
        arr_1[i] = np.nan
        ct+=1

print(arr_1)
print(ct)

[nan, 'B', 'C', 'D', nan, 'F', 'G', 'H', nan, nan, 'K', 'L', 'M', 'N', nan, 'P', 'Q', 'R', 'S', 'T', nan, '0', 'W', nan]
7
